mixed-port: 7890

allow-lan: true
bind-address: "*"

mode: rule

log-level: debug

external-controller: 127.0.0.1:9090

subscribes: &sub 
  - Neko
  - YuriTele

dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: true # when the false, response to AAAA questions will be empty
  # These nameservers are used to resolve the DNS nameserver hostnames below
  # Specify IP addresses only
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  use-hosts: true # lookup hosts and return IP record
  # search-domains: [local] # search domains for A/AAAA record
  # Hostnames in this list will not be resolved with fake IPs
  # i.e. questions to these domain names will always be answered with their real IP addresses
  fake-ip-filter:
    # --- (Local Area Network) ---
    - '*.lan'
    # --- (System Connnect Detection) ---
    - '*.archlinux.org'
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    # --- (Game Services) ---
    # > Nintendo Switch
    - '+.srv.nintendo.net'
    # > Sony PlayStation
    - '+.stun.playstation.net'
    # >  Microsoft Xbox
    - 'xbox.*.microsoft.com'
    - '+.xboxlive.com'
    # --- (Other) ---
    # > QQ Quick Login
    - 'localhost.ptlogin2.qq.com'
    # >  Golang
    - 'proxy.golang.org'
    # > STUN Server
    - 'stun.*.*'
    - 'stun.*.*.*'
  # Supports UDP, TCP, DoT, DoH. You can specify the port to connect to
  # All DNS questions are sent directly to the nameserver, without proxies involved
  # Clash answers the DNS question with the first result gathered
  nameserver:
    - tls://north.tex0n.net:789
    - quic://north.tex0n.net:785
    - https://north.tex0n.net:784/dns-query
    # - dhcp://en0 # DNS from DHCP
    - https://dns.alidns.com/dns-query # D
    - tls://dot.pub
  # Lookup domains via specific nameservers
  # nameserver-policy:
  #   'www.baidu.com': '114.114.114.114'
  #   '+.internal.crop.com': '10.0.0.1'

tun:
  enable: true
  stack: system
  auto-detect-interface: true
  auto-route: true
  dns-hijack:
  - any:53
  mtu: 9000
  # strict_route: true
  # inet4_route_address:
  # - 0.0.0.0/1
  # - 128.0.0.0/1
  # inet6_route_address:
  # - "::/1"
  # - "8000::/1"
  # endpoint_independent_nat: false
  # include_uid:
  # - 0
  # include_uid_range:
  # - 1000-99999
  # exclude_uid:
  #- 1000
  # exclude_uid_range:
  # - 1000-99999
  # include_android_user:
  # - 0
  # - 10
  # include_package:
  # - com.android.chrome
  # exclude_package:
  # - com.android.captiveportallogin

proxies:

proxy-groups:
  - name: PROXY
    type: select
    proxies:
    - 自动测试喵
    - 回退喵
    use: *sub # 引用锚点

  - name: 国内喵
    type: select
    proxies:
    - DIRECT
    - PROXY

  - name: 禁止通过喵
    type: select
    proxies:
    - REJECT
    - PROXY
    - DIRECT

  - name: 自动测试喵
    type: url-test
    use: *sub 
    url: http://www.gstatic.com/generate_204
    interval: 300

  - name: 回退喵
    type: fallback
    use: *sub 
    url: http://www.gstatic.com/generate_204
    interval: 300
  
  - name: Neko
    type: select
    use: 
    - Neko
  
  - name: YuriTele
    type: select
    use: 
    - YuriTele



proxy-providers:
  YuriTele:
    type: http
    url: "https://yuritele.com/link/Cihx2GRr2Ub4Ewek?clash=1"
    interval: 86400
    path: ./proxyset/YuriTele.yaml
    health-check:
      enable: true
      interval: 600
      lazy: true
      url: http://www.gstatic.com/generate_204
  
  Neko:
    type: http
    url: "https://nya.xgix.net/yurirepublic/api/v1/client/subscribe?token=854802ba2f163b7884d1414921457ca0" 
    interval: 86400
    path: ./proxyset/Neko.yaml
    health-check:
      enable: true
      interval: 600
      lazy: true
      url: http://www.gstatic.com/generate_204
    
rule-providers:

  Censor:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Sestea/Profiles/master/Clash/Provider/Censor.yaml"
    interval: 86400
    path: ./ruleset/Censor.yaml

  Streaming:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Sestea/Profiles/master/Clash/Provider/Streaming.yaml"
    path: ./ruleset/Streaming.yaml
    interval: 86400

  Block:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Sestea/Profiles/master/Clash/Provider/Block.yaml"
    path: ./ruleset/Block.yaml
    interval: 86400

  Global:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Sestea/Profiles/master/Clash/Provider/Global.yaml"
    path: ./ruleset/Global.yaml
    interval: 86400
   
  China:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://github.com/Sestea/Profiles/blob/master/Clash/Provider/China.yaml"
    path: ./ruleset/China.yaml
    interval: 86400


rules:
  - RULE-SET,Global,PROXY
  - RULE-SET,China,国内喵
  - RULE-SET,Block,禁止通过喵
  - RULE-SET,Censor,PROXY
  
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - RULE-SET,Streaming,PROXY
  - MATCH,PROXY,dns-failed
